#!/Users/satinderjitsingh/anaconda3/bin/python

'''
Even Fibonacci numbers

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
i=0
fib=[1,2]
while(True):
  new=fib[i] + fib[i+1]
  i=i+1
  if new<4_000_000:
    fib.append(new)
  else:
    break

sum=0

for elem in fib:
  if not elem%2:
    sum = sum + elem

print(sum)
